# Generated by Django 5.1.3 on 2024-11-13 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.AlterModelOptions(
            name='accommodation',
            options={'verbose_name': 'Accommodation', 'verbose_name_plural': 'Accommodations'},
        ),
        migrations.AddField(
            model_name='accommodation',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='available_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accommodation',
            name='max_guests',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccommodationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='accommodation_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='accommodation.accommodation')),
            ],
            options={
                'verbose_name': 'Accommodation Photo',
                'verbose_name_plural': 'Accommodation Photos',
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='accommodations', to='accommodation.amenity'),
        ),
    ]
