# Generated by Django 5.1.3 on 2024-11-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_amenity_alter_accommodation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
