# Generated by Django 5.1.3 on 2024-11-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0004_accommodation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationphoto',
            name='photo',
            field=models.FileField(upload_to='accommodation_photos/'),
        ),
    ]
