# Generated by Django 5.1.3 on 2024-11-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_telegram_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renter',
            options={'verbose_name': 'Renter', 'verbose_name_plural': 'Renters'},
        ),
    ]
